### ISSUE TITLE
Nux mp2 not found when scan

### ISSUE THREAD

**Issue by Zinnerxex** [tuntorius/mightier_amp#101]
I installed mightier amp and try to connect to my nux mp2 but i can't see my device when scan but when i go to midi/hid remote control i can see my device but can't connect. I'm using lasted firmware and 1.0.10 mightier amp. Any idea?

**Comment by tuntorius** [comment]
That is strange it appears under remote control but not in the main scan field. The app must show NUX amps only in the main scan window and other MIDI controllers in the remote control page. However, it filters them only by name as there is no other indication to guess if it's a NUX amp or not.
I can only guess, but if your mp2 is a more recent revision, maybe they have changed the Bluetooth name? Please, type the exact name as it appears in the remote control page.

**Comment by tuntorius** [comment]
> when i go to midi/hid remote control i can see my device

Please, I asked you specifically about this. What is the exact name you see on that page?

**Comment by Zinnerxex** [comment]
![Uploading Screenshot_20240403_145225.jpg…]()

**Comment by tuntorius** [comment]
Great, it's different. Thank you for noticing it appears under the remote control page, as this gave me a clue what is happening. They indeed have changed the name. I will publish an update soon.

**Comment by tuntorius** [comment]
You can't change the name, you'll have to wait for an update. I published it already but it will take several hours for Android and a day or two for iOS to appear in the app store.
