### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#11]
Hi tuntorius,

first of all, thanks for your great app. 

Having used it for a couple of days now, I came across a few things I feel could improve the app even further, so maybe you might consider changing/adding them:

* Support screen rotation. Many tablet stands only offer landscape position.
* Stretch the seven channel buttons, so they are larger and easier to hit. 
* Show name of active preset in the editor tab, when using a saved preset.
* Show if amp is connected in the editor tab. Maybe an icon that changes color and also works as a "Connect to amp button" at the same time?

Finally I wonder if anyone is aware of a forum, webpage, or Facebook group to discuss settings and share patches?

Hope my input is useful to you. Keep up the good work. A coffee is already coming your way.

Regards

**Comment by tuntorius** [comment]
Hi,
thanks for the kind words, the feedback and the coffee :)

1. Screen rotation was available before but there were problems with the editor view and I disabled it. I'm planning to fix that and reenable it again.
2. I guess you are using the previous version of the app? I added qr code scan and rearranged the buttons in 2 rows similar to the official one. I forgot to update it here in github, only in Play Store:
https://play.google.com/store/apps/details?id=com.tuntori.mightieramp&hl=bg&gl=US
Now I updated it here as well.
3. I'll see how I can fit that.
4. There's already such status in all tabs - top right. The bluetooth icon is greyed out if nothing is connected and when you connect an amp it becomes white and changes into a bluetooth connected icon (the one with dots arount the logo). Also the battery indicator appears.

as for preset sharing group, have a look at this one:
https://www.facebook.com/groups/nuxmightyplugairgroup

**Comment by TullyMore** [comment]
Hi,

thanks for your feedback.

You were right about the previous version. I upgraded to the current one and it looks great now. Alas I had to use the github version, as the Play Store didn't show me the app.

I assume, that you have to tick some boxes to indicate which Android versions and devices are supported, when uploading your app to the Play Store? I'm running a rooted 7.1.2 Android on a Nexus 7 (v 1, 2012) here. Would be nice, if I could install the app trough Play Store again, so I won't miss any of the updates.

Thanks also for the link to the Facebook group. I'm looking forward to share my presets, once I managed to create a decent one.

I noticed, that there was a question regarding the support for a foot switch. The Librarian app for my Boss Katana offers hotkey settings when using an attached keyboard. Maybe that would be worth considering?

It  works both with a regular keyboard, as well as a cordless one, connected via a USB OTG adapter. Currently I just removed the unnecessary keys and use the keyboard as is, but am planning on building a  pedalboard by using the keyboards electronic and proper footswitches.

Here's the link to this app, in case your planning to implement this feature:
[https://play.google.com/store/apps/details?id=com.appsforamps.katana&hl=de&gl=US](url)

It will tell you, that no amp is connected. Just choose the three stripes in the top left corner, then settings and scroll down to Hotkey settings. There you can select, which key you want to use for the available options.

**Comment by TullyMore** [comment]
Just noticed, that my Samsung S3 running Android 4.3 doesn't show your app in the Play Store either.
Happy to give you feedback if you wish, once it's installed.
Cheers

**Comment by tuntorius** [comment]
The app requires android 4.4 and up, so your S3 is a no go. It also requires bluetooth 4.0 support (for the BLE connection with mighty plug), which according to the specs is not present on the Nexus 7.
As for the controller support, that is one of the next features I'm planning to implement. I'll add the HID first cause it's easy and I can test it. I don't have any midi controller though. That will be tricky to implement without a device.

**Comment by Yimyai** [comment]
First, thanks for the app. It's really great. Love it.

It's fantastic news that you will be adding controller support - music to my ears ;-). This will really take the app to a level beyond anything else that is currently available. 
Coupled with a UHF stereo transmitter/receiver (Mighty Plug into the UHF transmitter - receiver plugged into mixer) this could give a completely wireless live system using only ultra portable equipment!

One coffee on it's way to you.

**Comment by Yimyai** [comment]
Forgot to mention that if you need some Beta testers (I have a couple of controllers) I would be happy to help

**Comment by Guitarltd** [comment]
Hi! Can you add +5/-5/+1/-1 bpm buttons to the metronome?
And is this possible to add tuner to the app?
Thanks for the app! It's awesome

**Comment by tuntorius** [comment]
@Yimyai thanks for your support. I appreciate it. I'm already working on the keyboard/hid input. I think in a week or so it will be ready.
@Guitarltd the additional bpm buttons is a good idea, I'll add them. 
As for the tuner it's not possible for the app to receive guitar audio. The amps simply don't transmit it. The only way is by using the phone mic, just like the rest of the tuner apps available in the app store. In fact I already tried that. However I found only one library that does pitch detection for the programming environment I'm using and it was inaccurate half of the time so I scrapped the idea.

**Comment by TullyMore** [comment]
Hi,
just letting you and potential other users of the app know, that it's running fine on a Nexus 7 (v 1, 2012), running Android 7.1.2, when installed using the mightierampX.X.X-v7a.apk. 
As you mentioned, it won't install on my Samsung S3 running Android 4.3.

**Comment by tuntorius** [comment]
@TullyMore This is what Google developer console shows about nexus 7 support:
https://gcdn.pbrd.co/images/KtcgqRgObh9g.png?o=1
As you can see both variants are supported. If there's green check on this page, then play store will show the app on that device. I have no idea what happens in your case.
Also for

**Comment by TullyMore** [comment]
Just found you comment. Thanks for checking.

To make sure, the installed package isn't interfering, I uninstalled it and rebooted Android.

Unfortunately the app still doesn't show up when searching for it in play store. Looking it up in the browser on Google play, it says, that my device isn't compatible with this version.

Maybe Google changed the support settings in the meantime? Especially, as I run a newer Android version, than the last official one for the Nexus?

Certainly would be nice to get the updates automatically, but I'm also happy to install the package manually.

**Comment by TullyMore** [comment]
That's odd. If I check for your app in the browser on play.google.com, it tells me, that the app isn't available for any of my devices. BUT, it also shows a button telling me, that it is installed :-) 

And yes, like I wrote above, I made sure it's uninstalled. 

Not trying to cause a fuss here, just letting you know, in case other users have a similar problem.

**Comment by Showtime13** [comment]
Hi @tuntorius! Thank you for the app, it's hard to overestimate how much more the mightier app gives (especially before the new update of Mighty app) than the default version.
I recently used the IR patcher, which is simply amazing! It gives you a totally different sound and so much more versatility! 

What came to my mind is, would it be possible to add a support VST3 or VST plugins? I'm more than sure you have considered that, and if it was so easy you'd do that a long time ago, but... do you think it's possible? Maybe some converter from VST to NUX Plug's format?

**Comment by Guitarltd** [comment]
Hi @tuntorius, your last update with add chocolate midi supporting is just amazing! Thanks a lot!
Could you please add hot key for midi to switch on/off the metronome and +5/-5 bpm knob? It would be awesome!

**Comment by Showtime13** [comment]
Hi @tuntorius, the app is great, but what I find uncomfortable is that each time I connect the Mighty Plug I have to go to USB settings and set it to Dry Out.
Would it be possible to add a support for an option that would save my previous USB settings set, so each time I connect it automatically sets the Dry Out and 100% input signal?

Thank you!

**Comment by Alexi-Zemcov** [comment]
Hey @tuntorius! @TullyMore asked for screen rotation above, so I created pull request about this feature:
https://github.com/tuntorius/mightier_amp/pull/33
Please check it out when possible.

**Comment by craig8ken** [comment]
Turn Bluetooth OFF or ON.
Hi @tuntorius, I was searching for control over the Mighty Air Bluetooth and found your wonderful Mightier Air app.
I want to turn Mighty Air Bluetooth feature OFF, to prevent interruptions while watching YouTube etc. 
 Prevent my Google Chromecast from interrupting Youtube content (guitar tutorials etc) with "Would you like to connect to NUX Mighty Air" while I'm actually using the amp.
Cheers!!
