### ISSUE TITLE
Fine control over Jam Track events

### ISSUE THREAD

**Issue by d00z3l** [tuntorius/mightier_amp#110]
You have built an awesome app, it is really appreciated. One enhancement that would be great is fine control over the event insertion point in the jam tracks. The current slider and left/right controls make it difficult to get the right spot. The Katana Go allows you to enter the exact time down to a tenth of a second. I assume that would be possible? It would be a very helpful enhancement.

![image](https://github.com/user-attachments/assets/cc31c159-fb8e-4332-97b0-a3af46a349dd)

**Comment by tuntorius** [comment]
I don't understand. Insertion by entering time is incredibly cumbersome. The way I made it in Mightier Amp is a lot more precise:
![gif-20240724-134008](https://github.com/user-attachments/assets/9524cacb-21b4-4221-976b-339fcd1c07b8)

**Comment by d00z3l** [comment]
I didn't know you could zoom, I will give that a try
