### ISSUE TITLE
Error value when edit "time" of dly/rvb in bpm

### ISSUE THREAD

**Issue by Guitarltd** [tuntorius/mightier_amp#14]
If you select bpm mode for time of Delay/Reverb etc settings - you can't type **bpm** value, because it still wait **ms** value

![photo_2021-09-28_14-31-26](https://user-images.githubusercontent.com/13440021/135078928-e7763d00-99a7-4878-8b26-549f0fcea7f9.jpg)

**Comment by tuntorius** [comment]
In fact it's not in ms either. It simply asks for value from 0 to 100 like the rest of the sliders. I'll fix it in the next release.
