### ISSUE TITLE
SDK?

### ISSUE THREAD

**Issue by Pemo11235** [tuntorius/mightier_amp#17]
Hi, I'm just bought a nux amp. I would like to give my contribution. 
Is there an SDK (released by Nux) ? Or you just reverse engineering the app?

Thanks :)

**Comment by Showtime13** [comment]
@JK5150 
Hi! You can use a standalone headphone amplifier or upload IRs (they might be louder), another option is to use sound isolating headphones.
I suspect the problem with **Louder** sound is that it will simply distort and the pushing the device over 100% of the sound it can produce will only cause clipping and sound distortion (not in a good way).

Have you tried using different headphones? The sound coming from the headphones depends on their sensitivity and impedance. You can try using 16 ohm headphones (IEMs), which will for sure give you a louder sound in most cases.
For example, with my M20x headphones, when I crank up the volume I only get silly sound (sounds bad), possibly clipping.

I may be wrong though, not sure how much this device can produce. The sound amplification worked well with PC though.

**Comment by JK5150** [comment]
Hello!
Thanks you for your advice! Tuntorus already gave it me 😊 I mean different IRs
My question was regarding live usage, but after my question on forum I already played couple of live shows and it seems that there is enough power in device 😊
So I think issue is closed 🍻
--
Отправлено из Mail.ru для Android пятница, 07 января 2022г., 18:04 +04:00 от Showtime13  ***@***.*** :

***@***.***
