### ISSUE TITLE
Crashed on android 4.4.2

### ISSUE THREAD

**Issue by karabas2011** [tuntorius/mightier_amp#20]
I have tried today's ver0.9.0
App is stopped on my 7" Samsung SM T231
The same with stock app.
Only old stock v2.2.2 works

**Comment by tuntorius** [comment]
Does version 0.8.8 works?

**Comment by karabas2011** [comment]
0.8.8 shows black screen
0.9.0 shows black screen and "Application stopped"

**Comment by karabas2011** [comment]
Sorry 0.8.8 shows black screen for a while, then starts.
0.9.0  Stopped 
[Uploading logcat_12-13-2021_17-05-44.txt…]()

**Comment by tuntorius** [comment]
Hi, thanks for the log. It confirms my suspicions. I added USB-MIDI support in 0.9.0. It is available in Android 6+ only, but I do a check before I try to use it to retain compatibility with older versions. I have a phone with 4.4 and it works with it so I thought I did that check correctly. Maybe I'm missing something. I'll take a more in-depth look.

**Comment by karabas2011** [comment]
Thanx!!!

**Comment by tuntorius** [comment]
Almost a year later, the bug is fixed.
