### ISSUE TITLE
Bass amps saving wrong volume level

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#22]
Just played around with the bass amps. To make them comparable, I set all sliders to 50 % and saved them to slots 4,5 and 6 on Mighty Amp. 

Switching between the slots, the percentage number for the level slider dropped to 42 %. This is true for all three bass amps.

I tested it for the following settings as well:

Set     Returned     Difference
100          84                 16
 90           75                 15
 80           67                 13
 70           59                 11
 60           51                   9
 50           42                   8
 40           34                   6
 30           26                   4
 20           17                   3
 10             8                   2
   0             0                   0

Saving the settings to the local device as a preset and then loading this preset, returns the correct level of 50 %.

**Comment by TullyMore** [comment]
I investigated further on this issue, as I realized, that the guitar volume level was behaving the same way.

Turnes out, this only happens on a Nexus 7 (2013) running LineageOS Android version 11. 

An older Nexus 7 (2012) running AOSP Grouper Android version 7.1.2 and a recent Samsung Galaxy running a stock Android 11 aren't affected.

Interestingly enough, the other slider values in the "Amp" tab arent't affected as well.

While playing around with this issue, I found, that each time I save the current values to the Mighty Air, the values are stored with half of the intended settings. If I set the slider to 100%, the saved value is 50%, if I save it again to the Mighty Air it's 25%, and so on.

As I mentioned, it's only present on LineageOS. A workaround is, to use the volume knob on the Mighty Air to set the volume in the app. Then save it to the Mighty Air. This way the volume is stored correctly.

As I have a workaround and this issue seems to be only relevant with LineageOS, I'm happy to close this issue, if it's of no further interest for you. Please let me know.

**Comment by tuntorius** [comment]
Thank you for the effort. The problem is that the "Global Volume" slider is wrongly added on top of the amp volume when a preset is saved. It's not an OS-related issue. You probably have it set at 50% on your LineageOS device and 100% on the rest. Sorry that you wasted so much time on something so simple.

**Comment by TullyMore** [comment]
Haha, you're right. Not a problem and thanks for pointing this out.
Happy to see, that you solved another issue, which leaves you more time to work on the next release. Looking forward to it ;-)
