### ISSUE TITLE
Mightier Amp won't connect to Mighty Air Midi

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#25]
Hi,

on a new phone here and mightier amp won't connect to mighty air midi.

It will connect through bluetooth and I can play a jam track from my local library using mightier amp, but it won't play the metronome and I can't use any of the editor features (changing channels, e.g.).

I'm on a Samsung Galaxy A52s 5G running Android 11 and Mightier Amp 0.9.0 installed through Google Play Store (tried the apk file from GitHub as well).

App permissions are given for camera, files, media and location. In mightier amp, the firmware version is set to Mighty Plug/Air v2.1 and device set to Mighty Plug/Air. The installed firmware however is v2.2!

Connecting with my old Nexus 7 with the same settings, version numbers, etc. on the other hand works.

**Comment by TullyMore** [comment]
Problem solved. Even so Mightier Amp app had permissions for location, the global location setting was disabled.

**Comment by tuntorius** [comment]
Thanks for informing me and it's great that you solved it! That's really something I've neglected. I should add a warning if the location setting is turned off.
