### ISSUE TITLE
Not working on NUX Mighty Lite BT fw v1.5

### ISSUE THREAD

**Issue by n0th1n6** [tuntorius/mightier_amp#27]
Hi, I tried it with a mighty lite BT but it was not able to connect. (Connection Failed.). I'd like to try to make it work, maybe build a version that I can test. How should I go about it? 

I manage to build the source and get a debug message, onClientConnectionState is 0. Here it is

> I/flutter ( 5987): Device connected
I/flutter ( 5987): just connected
W/ori.mightieram( 5987): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
D/FlutterBluePlugin( 5987): [onDescriptorWrite] uuid: 00002902-0000-1000-8000-00805f9b34fb status: 0
W/ori.mightieram( 5987): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
D/BluetoothGatt( 5987): onConnectionUpdated() - Device=CB:4E:FD:E3:B0:33 interval=16 latency=0 timeout=512 status=0
D/FlutterBluePlugin( 5987): [onCharacteristicWrite] uuid: 7772e5db-3868-4112-a1a9-f2669d106bf3 status: 0
D/BluetoothGatt( 5987): cancelOpen() - device: CB:4E:FD:E3:B0:33
D/BluetoothGatt( 5987): onClientConnectionState() - status=0 clientIf=12 device=CB:4E:FD:E3:B0:33
D/FlutterBluePlugin( 5987): [onConnectionStateChange] status: 0 newState: 0
D/BluetoothGatt( 5987): close()
D/BluetoothGatt( 5987): unregisterApp() - mClientIf=12
W/ori.mightieram( 5987): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
I/flutter ( 5987): Device disconnected
I/flutter ( 5987): Dev just disconnected!
I/flutter ( 5987): Device disconnected
I/flutter ( 5987): Dev just disconnected!

**Comment by tuntorius** [comment]
Hi, can you give it a try with versions 0.8.2 and 0.8.6 from the releases section:
https://github.com/tuntorius/mightier_amp/releases
If it works with 0.8.2 and not with 0.8.6 then I guess the new way I'm handling the firmware version message broke the BT Lite support.

**Comment by n0th1n6** [comment]
It works on 0.8.2, 0.8.6, 0.8.7, and 0.8.8 but not on 0.9. I have tested on two phones (MI8 and Oppo A9), the result is the same.
