### ISSUE TITLE
any chance of Chrome app port?

### ISSUE THREAD

**Issue by FrankOwen** [tuntorius/mightier_amp#28]
Seems like Android codebase should make this fairly easy to run as Chrome app? This would give more options to those of us who don't own Android devices. (As Chrome app, it could run on lots of platforms..)

Also, do you think it might run in ARC Welder? (new APK tester from Google for Chrome..)

**Comment by tuntorius** [comment]
Hi,

I don't see how this can happen. Chrome apps are basically websites written in html, javascript, etc.., packed together with the chrome browser. Nothing to do with android. If you mean installing the app on a Chromebook, then I've heard several people successfully installing it by sideloading the apk.

As for Arc welder, it's actually 5-6 years old and Google dropped it for a long time. All the Arc Welder apps you find in the Chrome Web Store are fake - probably spam or malware. Just look at the comments.
