### ISSUE TITLE
Feature request: Patch sorting

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#29]
Hi,

my patches are adding up and it would be nice, if they could be sorted in the Presets tab.
Any chance, to add a sorting feature? Either a simple auto alpha-numeric sorting as currently patches are saved in a wired order, or any other way to do it.

cheers

**Comment by tuntorius** [comment]
Hi, I just released a new version and I added patch and category reordering by drag and drop. You can reorder patches within the same or even different categories and also reorder the categories themselves.
