### ISSUE TITLE
Master volume possible? 

### ISSUE THREAD

**Issue by NikolajChristensen** [tuntorius/mightier_amp#3]
Hi there,

My inears are very effective so everything is extremely loud.

Is it posible to implement a master volume somewhere?

**Comment by tuntorius** [comment]
Hi,
my app just uses the available commands of the amp and there's no such master volume command. This must be implemented by NUX. You can reduce volume by using the amplifier level, IR gain or one of those: [https://www.amazon.com/Inline-Control-3-5MM-Headphones-Black/dp/B008DJTB32](https://www.amazon.com/Inline-Control-3-5MM-Headphones-Black/dp/B008DJTB32)

**Comment by NikolajChristensen** [comment]
Great tip about the volume control on the chord.

**Comment by JasonJAyalaP** [comment]
If, after a patch is loaded, the app set the gain and volume to the current knob position (possible?), the knobs could act as a master volume (for internal fx at least).
