### ISSUE TITLE
Is it possible to have the edit effect display what is currently in the device?

### ISSUE THREAD

**Issue by lewisde** [tuntorius/mightier_amp#4]
I've saved a couple presets and changed their slots. When I saved the next edit, both presets got applied but the edit screen did not reflect the preset settings.

**Comment by tuntorius** [comment]
There is no way (no such command) to retrieve what's currently on the device. That only happens once on connection establishment where the amp sends all its current presets/settings. Therefore what I'm doing is to always mirror what you see on the app screen and what is on the device by sending every adjustment to make sure they stay in sync. I'm sure that's what the original app is doing as well. 
It seems that you made them out of sync somehow. I don't exactly understand your steps to reproduce it. The only thing I could do is if I have a preset from the "Presets" page selected as the active one and change its channel(slot), neither the device changed its light color, nor the edit screen did. Is that what you encountered?
