### ISSUE TITLE
Charge value not precise and pseudo random

### ISSUE THREAD

**Issue by antonio-petricca** [tuntorius/mightier_amp#40]
Hi, today I received my NUX MP-2. I think it is very very impressive, for sure what I ever searched for! :)

Unfortunately I noticed an issue with charging. The power led is green, I connected the power supply. After some time the led goes off. I connect android management app, it reports me that the charge is at 100%, but after about 1 minute it reports me that it is 92% without using it. Why?

Does it maybe a software or hardware problem, or is  normal behaviour?

Thank you!

**Comment by tuntorius** [comment]
My app reports what the amp says. I think what you see is normal. My plug is at 100% only when it's still connected to a charger. When I disconnect it, the level drops to less than 90% in several minutes. Then it goes down slower. The battery life is about 2.5 hours, far from the claimed 4. This is not just my unit but many users have reported similar life. The led behavior you describe is normal. Not sure why they did it like this when the led can turn red as well.

The official app had a percentage display previously, but they replaced it with just 4 bars, most likely to prevent battery anxiety in people.

**Comment by antonio-petricca** [comment]
Thank you so much!
