### ISSUE TITLE
Suggestion: Online preset exchange

### ISSUE THREAD

**Issue by Taeon** [tuntorius/mightier_amp#5]
First of all I just wanted to express my appreciation for your efforts, this is a fantastic project. The app is excellent and the additions -- in particular, the ability to save multiple presets -- are really useful.

Anyway, I was wondering whether it might be useful to create a means for users to exchange presets easily. I was thinking along the lines of a central online preset repository: within the app, a user could export a preset to the repository, perhaps giving it a title and a brief description -- e.g. if it's for a particular artist, a specific song or or just a general style -- and maybe even have categories. 

Then other users could (again, from within the app) search and/or browse the repository and download any presets they find interesting.

Just a thought. 

Thanks again and keep up the great work!

**Comment by tuntorius** [comment]
I'm glad that you find the app useful. I also have that feature in mind among others, like an option to search backing track websites like guitarbackingtrack.com and backingtracks.co and add tracks to your jamtracks list. However I want to complete the features that are WIP currently.
Besides, there are like 20-30 active users of the app so I don't expect an extensive online presets library.

**Comment by Taeon** [comment]
Fair enough. Being able to search/download from backing track sites would be a fantastic feature.

> Besides, there are like 20-30 active users of the app so I don't expect an extensive online presets library.

I'm spreading the word about the app wherever I can!
