### ISSUE TITLE
Issue: Importing QR code image not working

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#50]
Hi,

minor issue, as it’s only affecting my Galaxy Tab A running Android 8.1.0. It’s working on Android 13.

Importing a QR code image results in all channels showing the same settings, which, on top of it, are not the settings of the imported preset.

Regards
TullyMore

Devices and versions:
Android 13 on Samsung Galaxy A52s 5G
Android 8.1.0 on Samsung Galaxy Tab A (2016)
Mightier Amp v0.9.6 with all permissions granted

**Comment by tuntorius** [comment]
Casued by "Do not keep activites" set to on in developer settings.
