### ISSUE TITLE
Issue: Scanning QR code not working

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#51]
Hi,

I can’t scan any QR codes, with either of my devices, but it’s working with the NUX Mighty Amp app.

On the Tab A, Mightier Amp simply shuts down with a pop up window to report this error.

On the Galaxy A52s, the camera function opens, but when scanning the QR code, nothing happens.

As far as I can see, permissions for both apps are granted.

Regards
TullyMore

Devices and versions:
Android 13 on Samsung Galaxy A52s 5G
Android 8.1.0 on Samsung Galaxy Tab A (2016)
Mightier Amp v0.9.6 with all permissions granted
Mighty Amp v2.3

**Comment by tuntorius** [comment]
Casued by "Do not keep activites" set to on in developer settings.
