### ISSUE TITLE
Issue: Order after sorting presets not persistent

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#55]
Hi,

thanks for adding the reordering option per drag and drop. Unfortunately, the new order sometimes isn’t persistent.

Some presets stay in place, while others move to the end of the list. I haven’t yet found any consistency in this behavior, but will keep an eye on it. Maybe you see what’s happening, when checking the relevant section in the code.

Regards
TullyMore

Devices and versions:
Android 13 on Samsung Galaxy A52s 5G
Android 8.1.0 on Samsung Galaxy Tab A (2016)
Mightier Amp v0.9.6 with all permissions granted

**Comment by tuntorius** [comment]
This is fixed in the latest 0.9.8 release.
