### ISSUE TITLE
Feature requeat- Mighty Space

### ISSUE THREAD

**Issue by marksd2167** [tuntorius/mightier_amp#56]
Please add support for Nux Mighty Space

**Comment by tuntorius** [comment]
Before releasing a version I want to make sure it works.
This is a web app version of Mightier Amp with an attempt to support it. Can you try to see if it works?
https://mightieramp.web.app/
Not all browsers support Bluetooth. In Android, it works with Chrome. You can also test it on a computer if it has a Bluetooth device. I think only Chrome, Edge, and Opera support it. Note that the web version is incomplete and many other things don't work.

**Comment by marksd2167** [comment]
Tested the link on my Samsung NoteUltra 20. phone. I was able to connect
the Nux Might Plug Pro and mess around with some of the presets without
issues.
I wasn't able to import any QR codes, but that feature might just not be
working.

Tested on my ThinkPad Laptop running Windows 11. I was able to open the web
link and see the app. I'm able to connect the Mighty Plug Pro via Bluetooth
to the Laptops, but I'm not able to connect to the MPPro in the app. It
scan and it finds the MPPro, but when it's in the window, I just can't
connect to it. See screenshot below.

[image: image.png]

If there is anything else you need me to test or try, let me know.
Mark.

**Comment by tuntorius** [comment]
New Mightier Amp 0.9.8 is out with Mighty Space support. Without the looper controls though. I don't have it and can't test how it works.
