### ISSUE TITLE
No more labels for sliders

### ISSUE THREAD

**Issue by antonio-petricca** [tuntorius/mightier_amp#61]
Hi, all the labels for sliders have disappeared. It no more possibile to change any settings.

The application unfortunately is no more useful.

Is it possibile to fix it?

Thank you so much! :)

**Comment by antonio-petricca** [comment]
No, I don't.

Il Lun 13 Mar 2023, 21:58 tuntorius ***@***.***> ha scritto:

**Comment by antonio-petricca** [comment]
This is the situation:

Il Lun 13 Mar 2023, 23:02 Antonio Petricca ***@***.***> ha
scritto:

**Comment by cho45** [comment]
I reproduce this in my environment. (v0.9.9/Android13)

However, immediately after startup, the label is displayed without any problem. The label disappears when I perform operations such as selecting tabs.

![Screenshot_20230314-111535](https://user-images.githubusercontent.com/3092/224875444-e73d6de9-cf03-4cc3-9851-043f56b31dc4.png)

**Comment by tuntorius** [comment]
I'm not sure why the accessibility mode is triggering for you.
@cho45 just like you pointed out, the check if accessibility feature is enabled is so simple that it's impossible to get wrong. That property - "accessibleNavigation" is not written by me. It's part of the MediaQuery class from the flutter framework. I'm just doing a simple 'if' check. The only explanation is a bug in it. It works for me and I haven't heard about this problem from other people. I also did a search for a bug in it but haven't found any posts or issues about it. I guess I'll replace it with native android code that checks. Hopefully, that one will work correctly.

The reason behind those sliders is that I was contacted a few times by blind people, who asked me if I can make the sliders work with the accessibility features. The easiest solution was to detect if a reader is active and replace them with standard ones, which are designed with that in mind.

**Comment by cho45** [comment]
I looked for something in my Android settings that would turn on "accessibleNavigation" and found that Bitwarden was enabled in "Accessibility". When I tried turning Bitwarden off, the situation did not reappear.

It appears that flutter's accessibleNavigation in Android can be turned on for functions other than screen readers.

I don't know why "accessibleNavigation" is false only immediately after startup, but I think this is another issue.

**Comment by antonio-petricca** [comment]
I tried enabling/disabling Talkback and nothing happened.

I reinstalled your wonderful app, but nothing happened again. 

:)

**Comment by antonio-petricca** [comment]
Issue solved: I removed all of my 4 four apps from accessibility!

**Comment by tuntorius** [comment]
Great that you found the reason, but it still is not the perfect solution if you want to keep those apps. I think I successfully added accessibility functions to my custom sliders, so the next version will not use accessibleNavigation.

**Comment by antonio-petricca** [comment]
Great! Thank you so much again!

Il Mer 15 Mar 2023, 21:12 tuntorius ***@***.***> ha scritto:
