### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [tuntorius/mightier_amp#62]
ref: https://gitlab.com/fdroid/fdroiddata/-/commit/5bc1622dc21d76e268486ede612c6e5c37414990

ref: https://gitlab.com/fdroid/fdroiddata/-/commit/dbe89937c58b9c36552afa4cb49b431167963b1e

**Comment by licaon-kter** [comment]
@ashimokawa ^^^

**Comment by ashimokawa** [comment]
@licaon-kter 

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12746

**Comment by licaon-kter** [comment]
version 0.9.11 was not picked up because the version was not bumped: https://github.com/tuntorius/mightier_amp/blob/v0.9.11/pubspec.yaml#L18

**Comment by ashimokawa** [comment]
@tuntorius 

Your v0.9.11 tag is before the version bump. What about the published apk? Which commit does it correspond to?

I was assuming a3a64a5dd17c4b4f941de2d47c437324d7555ebc where the bump happened

But not sure whether it is rather fd1aa582d0ca3f7fc549a1a2ae22cd659a3f52d0 which had a CI build
