### ISSUE TITLE
iOS mightier_amp unable to load backing tracks

### ISSUE THREAD

**Issue by DaveM009** [tuntorius/mightier_amp#63]
Several issues identified in current iOS release:
1. Adding tracks is not possible without an Apple Music subscription as +icon for adding songs to Tracks only opens an empty Apple Music Playlist.  There is currently no option available to browse for locally stored backing tracks.
2. With an active Apple Music subscription, selecting a song from an Apple Music Playlist fails to save the song into the Track list. The Track list remains empty.

Edit: Apple Playlist working in iOS 15.7.3 (older iPhone) not IOS 16.4.1a on iPhone and iPad. Still unable to browse for Local files.

**Comment by tuntorius** [comment]
The current version can load tracks from the Media Library only - that is when you sync tracks from your computer, which will appear in the Apple Music app. I didn't know that the tracks from the Apple Music subscription will appear as well. Those are unplayable in Mightier Amp due to DRM, but there's a way to hide them, which I'll do in the next update.
I don't know why the newer iOS versions don't let you pick from tracks that you synced manually. Unfortunately, my iPhone is too old and can't update to the latest iOS.
I'll add browsing for tracks using a file picker in the next update. It will let you add not only local tracks but tracks from iCloud, Google Drive, and any other cloud services that you have installed.
All this comes from the fact I'm new to iOS and not familiar with how people add their music. I thought most users sync their music with the media library.

**Comment by DaveM009** [comment]
I thought most users sync their music with the media library.Synching requires access to a pc/Mac running iTunes. Without Apple sub, with Win 11 on a very old i3 laptop with 2 gb mem, you need to connect iPad/iPhone to laptop, copy the files to desktop, open iTunes and drag them into mighty amp app. It’s quite tedious on an old clunker.With backing tracks already on iPhone/iPad the ideal solution would be file picker and then add directly mighty plug. I used to save my own music to Apple media library but when Apple Music sub ran out it empties the media library including your own music files. My old iPhone 6s Plus on iOS 15.7.3 can save tracks from music library but it is wanting to update to 15.7.5 so hopefully this doesn’t break the track saving. My iPad and iPhone 12 mini can’t save tracks from music library. iOS 16.4 . Anyway to fix this? Hopefully the file picker helps with saving local media.I didn't know that the tracks from the Apple Music subscription will appear as well. Those are unplayable in Mightier Amp due to DRM, but there's a way to hide them, which I'll do in the next update.The Apple Music files saved in the mightier amp app on my 6s actually do play. Tracks only show up with an active sub so I would expect them to play. No active sub and media library is empty, so nothing to load. I don’t think you need to hide it, just need to be able to choose from either Apple Music or Files.Here’s how it looks on just chords track selector. Files gives you file access and Apple Music accesses media library.Sent from my iPadOn 16 May 2023, at 8:23 pm, tuntorius ***@***.***> wrote:﻿
The current version can load tracks from the Media Library only - that is when you sync tracks from your computer, which will appear in the Apple Music app. I didn't know that the tracks from the Apple Music subscription will appear as well. Those are unplayable in Mightier Amp due to DRM, but there's a way to hide them, which I'll do in the next update.
I don't know why the newer iOS versions don't let you pick from tracks that you synced manually. Unfortunately, my iPhone is too old and can't update to the latest iOS.
I'll add browsing for tracks using a file picker in the next update. It will let you add not only local tracks but tracks from iCloud, Google Drive, and any other cloud services that you have installed.
All this comes from the fact I'm new to iOS and not familiar with how people add their music. I thought most users sync their music with the media library.

**Comment by DaveM009** [comment]
@tuntorius  Any progress on a fix/update for iOS? Currently it’s unable to load ANY backing tracks on iOS 16. Your app is so much better than the Nux version that I use it regardless of backing track issue (and use Bluetooth for BT’s), but it would be really nice to be able to have them on the app. Happy to test any beta via TestFlight.

**Comment by DaveM009** [comment]
Latest beta 1.0.1 (39) 
Still unable to access tracks. The previous version was able to load Apple Library tracks on an earlier iOS version (ios15) phone, but not iOS 16 iPad/iPhone. 
Unfortunately the current beta not longer accesses tracks on either version of iOS.

**Comment by DaveM009** [comment]
Beta 1.0.2 the file picker switching to track edit and back to file picker is no longer crashing app.

**Comment by DaveM009** [comment]
Beta 1.0.2.(42)
Connects to MP3 Pro but Drums no longer working. Other features working
Connects to Mighty BT 20 but incorrectly reads fx settings for the selected amp style.

**Comment by DaveM009** [comment]
Beta 1.0.2 (43) 
MP3 track edit and drums working again.
Unable to connect to Mighty BT 20 amp.
