### ISSUE TITLE
Noise Gate on BT8?

### ISSUE THREAD

**Issue by ashimokawa** [tuntorius/mightier_amp#64]
Not sure if Noise Gate does anything on BT8, is this support to operate on instrument input? If so I cannot hear any difference when playing with it.

I unterstand that BT8 is untested anyway. Maybe someone with the official app can confirm whether noise gate is supported on this device or not?

**Comment by tuntorius** [comment]
If it's the same as Mighty Plug/Air, then it must operate on instrument input.
There was a bug that I fixed recently - the on/off state of the first effect was not toggled, but it happens only when loading preset from the list. It works when the state is changed manually.
What about the official app - does it work with it?
Another reason might be that the MIDI CC command is wrong.

**Comment by ashimokawa** [comment]
I never tested the official app, but I guess I will have to now ;)

On the latest release the noise gate still seems to do nothing, so at least it is not that but that got fixed recently ;)

**Comment by ashimokawa** [comment]
Sorry, the official app behaves the same. I do not hear a difference when togglint.

The noise I hear seems to come from the AC plug, so wonder I cannot control this with the noise gate. When I unplug the AMP from AC I hear a clear sound for a second before the capacitors are drained and the amp turns off. Wow. now I need to find some clever way to fix that.

**Comment by ashimokawa** [comment]
Just because the internet does not know (now it does)

**The Mighty Amp 8BT is super-noisy when on AC power (at least in my house with 230V/50Hz), it sounds way better when on batteries.** 

Tried two different AC adapters.

Back to topic: I cannot hear any difference from the guitar input when toggling noise gate neither official app nor mightier_map.
