### ISSUE TITLE
Feature Request: midi remote control tap delay

### ISSUE THREAD

**Issue by Agosti7** [tuntorius/mightier_amp#66]
Thank you for this amazing app. I dont know if this is already implemented or if there is a work around but I did not find a remote control parameter for tap delay. Can tap tempo for delay be implemented for the remote control midi?
Can the tuner be implemented in the remote control midi too?

**Comment by tuntorius** [comment]
The delay tap tempo midi hotkey has been available for a long time. It's there with the rest of the delay parameters.
I added a tuner hotkey in the latest update.
