### ISSUE TITLE
Feature Request: Additional EQ for guitar signal

### ISSUE THREAD

**Issue by TullyMore** [tuntorius/mightier_amp#68]
Hi,

while the Mighty Air sounds pretty decent using headphones, it lacks a lot of bass using its inbuilt speakers. This can be solved, by using the EQ in the EFX section. Unfortunately you then can't use any of the other effects like compressor, boost, etc.

As I assume, that this has to be solved by NUX with a firmware update (which most likely never will happen), I wonder if a 3 band EQ could be added to MightierAmp to shape the guitar signal.

regards
TullyMore

**Comment by UN-DRE** [comment]
TullyMore, the feature you are requesting is already implemented in both Mightier App and the stock Nux app. Go to settings and Speaker EQ, it's 10-band. While you are at it you can also adjust the the EQ for BT sound separately from the guitar output. It's a global setting that affects all presets.

**Comment by TullyMore** [comment]
Hi UN-DRE,

thanks for your comment. Unfortunately I can't find the settings you describe. 

When selecting the cogwheel symbol to access the settings, I don't get a Speaker EQ entry. What I get is "USB audio settings", where I can choose between normal/ream/dry out and "Bluetoothh audio EQ list" with a list of predefined settings e.g. acoustic, blues, etc.

App version is 1.0.6 from the app store and Mighty Air firmware should be the latest.

**Comment by UN-DRE** [comment]
Okay, sorry, I just realized you were talking about Mighty Air, while I was referring to Mighty Space. 
![image](https://github.com/tuntorius/mightier_amp/assets/147803380/4e821d9c-9610-4b48-bf4b-bb25005c1313)
Mighty Air doesn't seem to have this speaker tuning functionality. Then it's up to Tuntorius to say whether it is possible to imprement it.

**Comment by tuntorius** [comment]
This is not possible. Whatever you can do with the amplifier tone controls or the EQ in the EFX section - that's it.
The EQ in the settings of Mighty Air is for Bluetooth (Backing tracks) only. It doesn't influence the guitar sound.
