### ISSUE TITLE
Different Gain, EQ and Output levels-Wide model disparities

### ISSUE THREAD

**Issue by RexTee** [tuntorius/mightier_amp#7]
Hi:

First of all thank you for creating this very helpful tool. The MP-2 is fantastic out of the box, but I think it's fair to say that you've both made it more usable, and shown that there is potential for even more improvements.

One of those improvements would be to address the gain, eq and output levels and profiles of different amp models. To my ear, the Plexi and Lead 100 models are not usable because no configuration of gain, output, eq , cab and cab output level will yield anything other than a VERY overdriven sonic profile. Turning down the guitar cleans it up a bit, but the tone is not there. 

Is there a way to put each model on the same footing? The Tweed Deluxe model is fantastic, and I use it most of the times along with the Twin model. Both as clean or overdriven as I need. And both of these have the balls of the amp they model. Others just sound like different fuzz boxes at different levels of drive, with almost no tonal difference at all. 

By chance, I discovered that switching the stock  assigned 412gb cab on the Fireman model from GB412 to 1960412 gave the model a new life and put it in the sonic territory that the Marshall models should be in. The Ac30 model is basically useless, with or without the "top boost" fx. 

Finally, I found that increasing the speaker db up to almost max improves every model as much as it can be improved. 

It would be great if you could suggest or create a solution to this issue. I just know that there is much more lurking under the hood of the MP-2, and even so it's an excellent tool as is.

Regards, and thanks again.

**Comment by tuntorius** [comment]
Hi,
Sorry for answering so late. I was quite busy on my main job that I couldn't focus on something else for a while.
Unfortunately what you're asking is impossible to do using the phone app. All the controls, dsp processing etc... are in the firmware of the unit which I have no access to. It simply exposes a fixed set of controls using a bunch of MIDI commands that I've exposed in the app. If you have in mind something like expanding the range of the sliders, that is impossible as well. Every slider has 128 distinct values - you can't go below or above that. This is a limitation of  the MIDI protocol.

**Comment by RexTee** [comment]
Thanks for explaining that. I guess the amp models are simply dependent on
the ear of whoever designs them.
Still a great app!
