### ISSUE TITLE
Advanced backing track player functions

### ISSUE THREAD

**Issue by enotiqPoloskun** [tuntorius/mightier_amp#78]
Please add functions like play once, or when the track stops playing switch to the next one then pause like in AIMP. For now it plays track after track which is suitable for listening the music but not for backing tracks player. The only reason I think it's need to be added instead of just using AIMP is that AIMP can't switch preset in the marked spots like this and official app do. Also thank you for this app it's really cool.

**Comment by tuntorius** [comment]
There is already the "Auto advance" option which does exactly that. When a track is finished, it puts the next one on pause and waits for you to hit play or use a midi controller assigned to the play/pause function.
