### ISSUE TITLE
Feature request: Wah/LP filter effect

### ISSUE THREAD

**Issue by UN-DRE** [tuntorius/mightier_amp#79]
Dear Tuntorius, thank you very much for the amazing app! 

Is it possible to implement new effects, like Wah/Filter pedal with frequency sweep? 

I was experimenting with a midi controller expression pedal, and using the app's existing functionality it is already possible to sweep through "Cut" on AC30 amp model, but the effect is not drammatic enough to qualify as a Wah/filter pedal. 
I also tried sweeping through Tone on Fuzz pedal, with similar results. 
Sweeping through HF cut on impulse reponse block is even less effective because the resonance Q is low and cut-off frequency does not go down low enough.

Perhaps a new effect pedal could be added or an existing effect pedal or the speaker IR block could be modified to add adjustable high Q and to sweep the resonance fequency low enough using an expression pedal.

**Comment by tuntorius** [comment]
Hi,
I'm glad you find my app useful. Unfortunately, it's not possible to add new blocks, effects, or any kind of DSP processing. My app can't alter the firmware and is merely a remote control.
Maybe you've seen that it adds 8 additional amp models to MP-3 and Mighty Space and that made you think new FX can be added. Actually, they were already in the firmware. The official app doesn't list them.
