### ISSUE TITLE
Looper with metronome ?

### ISSUE THREAD

**Issue by Delamorenaa** [tuntorius/mightier_amp#8]
What about a looper function with the metronome ?

Thanks !

Delas

**Comment by Delamorenaa** [comment]
I was wondering if there was an android app to record the sound produced by a BTH device ? Then it could be used as a backing track in the mightier amp app

**Comment by tuntorius** [comment]
Hi,
unfortunately what you are asking is impossible because the guitar audio of the amp is never sent to the phone. The bluetooth audio connection is only one way - phone -> mighty plug.

**Comment by Delamorenaa** [comment]
Hi,

Now I better understand, maybe If I used the headphone output I can doing
it by plugin it into my phone but I have no idea if it is feasible and
which app to use.

Do you know ?

Regards,

Le sam. 31 juil. 2021 à 07:10, tuntorius ***@***.***> a
écrit :

**Comment by tuntorius** [comment]
If you find the right cable there are apps like Tonebridge, Amplitube, Deplike. However, the latency of the phone audio input is so huge it makes it practically impossible to play. Some of those apps claim that if you use an usb audio interface there is almost zero latency. I haven't tried it. Note that the mighty plug itself becomes an audio interface if you plug it using an usb otg cable.

You can plug it into an fx pedal or a modeling amp instead, it might work.

**Comment by JK5150** [comment]
All of these apps sounds more and more bad vs Nux
I think - there is good idea if you run some kind of record app ( e.g. WaveEditor), plug Nux to the phone via OTG - and you can record it :)
--
Отправлено из Mail.ru для Android понедельник, 02 августа 2021г., 11:47 +04:00 от tuntorius  ***@***.*** :
