### ISSUE TITLE
Presets button stops working (Landscape Mode)

### ISSUE THREAD

**Issue by UsulusU** [tuntorius/mightier_amp#80]
Hello,
So far, I only saw this issue when your (great) app is in Landscape Mode. after few minutes the button allowing to list the saved presets stops working. In fact it's seems the pressure area represented by a circle appears to be behind the button, and no longer above it. 
I thought I saw the report of this issue somewhere but I can't find where, so maybe I was dreaming!
And thank you very much for your work, I use your application on a daily basis!

**Comment by UsulusU** [comment]
Hello
The buttons are on the left in my Landscape Mode. The screenshot shows the pressure area behind the button :
![Screenshot_20231018_183645_com tuntori mightieramp](https://github.com/tuntorius/mightier_amp/assets/147990687/5dd9d8d6-b651-4f82-9598-ffc01bc53031)

**Comment by Blackace65** [comment]
Wish I would have saw this post earlier as I just opened a issue on the exact same thing. Will follow

**Comment by tuntorius** [comment]
it's fixed and will be out with the next version that will come in about a week.

**Comment by UsulusU** [comment]
What great news!
Thank you very much for your time and work!
