### ISSUE TITLE
USB MIDI controller settings not saved

### ISSUE THREAD

**Issue by UN-DRE** [tuntorius/mightier_amp#81]
Dear Tuntorius, 
I'm able to connect my MIDI pedal with foot switches by USB cable to my  phone and assign it control gain and turn  effects on and off. However, these assignments are lost between playing sessions. If I just disconnect and reconnect the cable from the phone the settings remain. However if I connect the next day, the app doesn't seem to remember the midi device, I need to find it again and all the assignments are gone.

**Comment by tuntorius** [comment]
Hi,
Is this happening on Android or iOS? I have tested USB MIDI devices on my Android phone many times, and there are no problems. However, I don't have a USB OTG cable for my iPhone to test on iOS.
Are the settings still lost if you close the app and reopen it immediately instead of waiting a long time?

**Comment by UN-DRE** [comment]
This is happening on Android on Google Pixel 4 xl. I'm using an OTG dongle that came with the phone to adapt from USB type A to USB type C to connect to my phone.
--
Sent from Mail.ru app for Android Friday, 27 October 2023, 06:52PM +03:00 from tuntorius  ***@***.*** :

**Comment by tuntorius** [comment]
What about my last question?
Also, is your MIDI pedal changing its name, or does it have some special symbol in its name? The settings are saved per device name, and if it has some special symbols like quotes it may fail to save.

**Comment by UN-DRE** [comment]
1. When the app is closed and reopened, it forgets about the midi controller, however after the controller scan is performed, it finds the controller with the same code and remembers the CC assignments.
2. If the midi controller is disconnected from the phone USB and reconnected in a few seconds,  the app loses the controller, and after a rescan, the controller is assigned a different name ("Arduino LLC Arduino Leonardo#206 MIDI 1.0" became "Arduino LLC Arduino Leonardo#930 MIDI 1.0") and of course, the CC assignments are lost.

**Comment by tuntorius** [comment]
I'm sure a device is not supposed to change its name like that. If this is a DIY Arduino pedal, its code should be fixed.

**Comment by UN-DRE** [comment]
It is a custom-made Arduino midi pedal. Thank you for clarifying that the issue is with my device. Although unfortunately I don't think, it is feasible to fix it, as the developer lives too far away to make it worth the shipment back and forth and I cannot fix it myself. 
I will close this issue. Thanks!

**Comment by tuntorius** [comment]
In that case, I'll add some code to match this name and strip the number from it. It's not the first time, anyway. The very popular MVave chocolate footswitch has an incorrect BLE advertising, and I had to apply a similar fix.

**Comment by tuntorius** [comment]
I'm reopening the issue because this might be a case with some Android phones, not with your MIDI controller. Recently I saw a phone that showed the same kind of hash sign and number in several MIDI controllers from different manufacturers.
So, instead of a fix specific to your case, I made the app to find numbers in this format and remove them from the name. The fix is in the latest update from yesterday. You can test it.

**Comment by UN-DRE** [comment]
Dear Tuntorius, I was able to test the latest update and unfortunately the pedal commands are no longer registered by the app. The Pedal is detected with no hash or number (Arduino LLC Arduino Leonardo MIDI 1.0) but I cannot assign any parameter or effect changes any more.

**Comment by UN-DRE** [comment]
Bump

**Comment by UN-DRE** [comment]
The controller is now recognized and settings are saved if the device is reconnected! I think this issue can be closed!
Thank you very much!
