### ISSUE TITLE
Navigating between effect pages shouldn't add undo/redo levels

### ISSUE THREAD

**Issue by xko** [tuntorius/mightier_amp#83]
.. and the other way around - pressing undo/redo shouldn't take me to different effect page. Same about "mirror" button.
Example:

- I tweaked my AMP and want to compare to where i started
- I press the "mirror" - sound changes back, but it takes me to the GATE page which I never changed
- I go to the AMP page again to see the original settings
- OOPS - my tweaks are now lost and undo/redo/mirror only switch between GATE and AMP pages

**Comment by tuntorius** [comment]
This is fixed in the latest version from yesterday. Navigation is not added to the undo stack anymore and you won't lose your tweaks that way.
However, I do not agree that pressing undo/redo shouldn't switch the UI to a different page. The user must be aware what has been changed.

**Comment by xko** [comment]
Thanks a lot! Looking forward to store update!
As to page switching: I mean #2 in my scenario - it shouldn't take me to the page I never changed. Switching to the page which did change at particular step is of course good.

**Comment by tuntorius** [comment]
Then it's all good. The update is live for a few days. You should be able to update.
