### ISSUE TITLE
Control via wireless (BLE) midi controller

### ISSUE THREAD

**Issue by Yimyai** [tuntorius/mightier_amp#9]
I'm not sure if you are aware of the Boss Katana app (Katana Librarian) but similar functionality would enable this app to send the NUX Might Plug to a whole other level. 
If Mightier Amp could connect to a BLE device (such as Airstep) AND the app has a "hotkey" function such as the Katana Librarian app, then the Airstep (which can send HID commands as well as midi) could act as a wireless controller for Mightier Amp., enabling the user to control the NUX with a wireless foot controller. Imagine being able to turn effects on and off and step through the presets.

To move the app even further into the realms of "unbelievable" would be to add "Banking". This would enable the user to create perhaps generic settings. Bank A could be "Rock" which would allow the storing of 4 presets (mapped to each of the button colours on the device) with each preset having different effects turned on/off or with different amps. Bank B could be "Pop" again with up to 4 presets stored, Bank C "Metal" etc. Then in the app when a user selects a bank it automatically loads the 4 stored presets in the app to the device. Similarly it could be used to create a "set list" one bank per song.

The functionality of the 2 suggestions above - combined - would enable the app to transcend from "good" to " absolutely incredible"

**Comment by tuntorius** [comment]
I have started working on this and have some progress. The app will support not only HID and BLE MIDI, but also wired USB-MIDI controllers using an otg cable. In the other thread I said I don't have a controller to test it, but found an app that emulates wireless midi controller and I'm using a second phone as a midi controller. I also have a midi keyboard to test USB MIDI. Well, it only sends note on/off messages but that's enough. The USB-MIDI support requires at least android 6 I think.

**Comment by Yimyai** [comment]
Hi, great news, thanks for the update. I'm really looking forward to this. The offer still stands if you would like help with testing :-)

**Comment by tuntorius** [comment]
Hi, I released the new version of the app yesterday and it's now live in the play store.

**Comment by Yimyai** [comment]
Thank you so much. I have been testing the remote midi functions and they work like a charm. This is absolutely brilliant. 
I have an Xsonic Airstep setup to change the channels and an Airstep Lite to turn effects on/off and it works perfectly. I will check out the Preset functions too.  
Your app deserves wider recognition. It is better than anything else currently available by a very long way. You should start charging for it, it is totally worth it. 

P.S. I am having another idea about integrating this with something like BandHelper - a free app on both Android and ios - to automatically change channels and effects upon song selection in BandHelper

Another cup of coffee will be on it's way to you tomorrow :-)

**Comment by JK5150** [comment]
Hello all! Who tried to use some BT controller with it? Who could guess - could I use that for channel switching?=) https://aliexpress.ru/item/1005003308021245.html
thanks you in advance!

**Comment by winswahwah** [comment]
> Hello all! Who tried to use some BT controller with it? Who could guess - could I use that for channel switching?=) https://aliexpress.ru/item/1005003308021245.html thanks you in advance!

It's working just fine. But you need to configure the M-VAVE as the keyboard using the CubeSuit application. Then configure the HID Input control in the Mightier Amp application.
