### ISSUE TITLE
nux 20BT custom tracks from phone?

### ISSUE THREAD

**Issue by Cobr3n** [tuntorius/mightier_amp#93]
Can I enable custom tracks from an andoid phone? I don't see this feature in the app

**Comment by Cobr3n** [comment]
![5555](https://github.com/tuntorius/mightier_amp/assets/25749976/90bc31e6-241c-446d-a11f-0c8ade42f46b)
PS: dont see tab **Custom** if select **nux 20BT** device

**Comment by tuntorius** [comment]
You are referring to the wrong app. The screenshot is from the official app. This repository is about the alternative - Mightier Amp. You may give it a try.
